version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    cooldown:
      default-days: 7

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  # Dependabot for Implementations (Harnesses)
  # ------------------------------------------

  - package-ecosystem: "npm"
    directory: "/implementations/js-hyperjump"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  # ignore: python-jsonschema - installs the latest (unpinned) version

  - package-ecosystem: "gradle"
    directory: "/implementations/java-json-schema"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  # Dependabot for Dockerfiles
  # --------------------------

  # See dependabot/dependabot-core#1015 or dependabot/dependabot-core#2178,
  # this doesn't happen automatically, so hooray, manual list.

  - package-ecosystem: "docker"
    directory: "/implementations/js-hyperjump"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/implementations/python-jsonschema"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/implementations/java-json-schema"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/bowtie/tests/fauxmplementations/envsonschema"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/bowtie/tests/fauxmplementations/lintsonschema"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
