image:
  file: .gitpod.Dockerfile

additionalRepositories:
  - url: https://github.com/json-schema-org/JSON-Schema-Test-Suite
    checkoutLocation: json-schema-test-suite

  # TODO: referencing-suite and others, once Bowtie supports them

tasks:
  - name: Populate MOTD with documentation
    init: sudo chown -R gitpod:gitpod /etc/motd && cp /workspace/bowtie/docs/motd.txt /etc/motd

  - name: Install Bowtie
    init: python3 -m pip install -r requirements.txt -e . && pyenv rehash

  - name: Pull Bowtie Images
    init: for each in $(bowtie filter-implementations); do docker pull ghcr.io/bowtie-json-schema/$each; done

  - name: Open Bowtie Documentation by default in web-ui
    init: gp open /workspace/bowtie/docs/motd.txt
