version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - inkscape
  tools:
    python: "3.12"

  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install -r docs/requirements.txt

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

formats: all
