/**
 * Auto-generated meta-schema loader
 * Generated by: jetvalidator-meta load
 *
 * Usage:
 *   import { loadDraft07, loadAllMetaSchemas } from './loader.mjs';
 *
 *   const jetValidator = new JetValidator();
 *   loadDraft07(jetValidator); // Load specific version
 *   // OR
 *   loadAllMetaSchemas(jetValidator); // Load all versions
 */

import schema_draft_06 from './draft-06/schema.json' with { type: "json" };

import schema_draft_07 from './draft-07/schema.json' with { type: "json" };

import schema_draft_2019_09 from './draft/2019-09/schema.json' with { type: "json" };
import schema_draft_2019_09_core from './draft/2019-09/meta/core.json' with { type: "json" };
import schema_draft_2019_09_applicator from './draft/2019-09/meta/applicator.json' with { type: "json" };
import schema_draft_2019_09_validation from './draft/2019-09/meta/validation.json' with { type: "json" };
import schema_draft_2019_09_meta_data from './draft/2019-09/meta/meta-data.json' with { type: "json" };
import schema_draft_2019_09_format from './draft/2019-09/meta/format.json' with { type: "json" };
import schema_draft_2019_09_content from './draft/2019-09/meta/content.json' with { type: "json" };

import schema_draft_2020_12 from './draft/2020-12/schema.json' with { type: "json" };
import schema_draft_2020_12_core from './draft/2020-12/meta/core.json' with { type: "json" };
import schema_draft_2020_12_applicator from './draft/2020-12/meta/applicator.json' with { type: "json" };
import schema_draft_2020_12_unevaluated from './draft/2020-12/meta/unevaluated.json' with { type: "json" };
import schema_draft_2020_12_validation from './draft/2020-12/meta/validation.json' with { type: "json" };
import schema_draft_2020_12_meta_data from './draft/2020-12/meta/meta-data.json' with { type: "json" };
import schema_draft_2020_12_format_annotation from './draft/2020-12/meta/format-annotation.json' with { type: "json" };
import schema_draft_2020_12_content from './draft/2020-12/meta/content.json' with { type: "json" };


export function loadDraft06(jetValidator) {
  jetValidator.addMetaSchema(schema_draft_06, 'https://json-schema.org/draft-06/schema');
  jetValidator.addMetaSchema(schema_draft_06, 'draft-06');

}

export function loadDraft07(jetValidator) {
  jetValidator.addMetaSchema(schema_draft_07, 'https://json-schema.org/draft-07/schema');
  jetValidator.addMetaSchema(schema_draft_07, 'draft-07');

}

export function loadDraft201909(jetValidator) {
  jetValidator.addMetaSchema(schema_draft_2019_09, 'https://json-schema.org/draft/2019-09/schema');
  jetValidator.addMetaSchema(schema_draft_2019_09, 'draft/2019-09');

  jetValidator.addMetaSchema(schema_draft_2019_09_core, 'https://json-schema.org/draft/2019-09/meta/core');
  jetValidator.addMetaSchema(schema_draft_2019_09_core, 'draft/2019-09/meta/core');
  jetValidator.addMetaSchema(schema_draft_2019_09_applicator, 'https://json-schema.org/draft/2019-09/meta/applicator');
  jetValidator.addMetaSchema(schema_draft_2019_09_applicator, 'draft/2019-09/meta/applicator');
  jetValidator.addMetaSchema(schema_draft_2019_09_validation, 'https://json-schema.org/draft/2019-09/meta/validation');
  jetValidator.addMetaSchema(schema_draft_2019_09_validation, 'draft/2019-09/meta/validation');
  jetValidator.addMetaSchema(schema_draft_2019_09_meta_data, 'https://json-schema.org/draft/2019-09/meta/meta-data');
  jetValidator.addMetaSchema(schema_draft_2019_09_meta_data, 'draft/2019-09/meta/meta-data');
  jetValidator.addMetaSchema(schema_draft_2019_09_format, 'https://json-schema.org/draft/2019-09/meta/format');
  jetValidator.addMetaSchema(schema_draft_2019_09_format, 'draft/2019-09/meta/format');
  jetValidator.addMetaSchema(schema_draft_2019_09_content, 'https://json-schema.org/draft/2019-09/meta/content');
  jetValidator.addMetaSchema(schema_draft_2019_09_content, 'draft/2019-09/meta/content');
}

export function loadDraft202012(jetValidator) {
  jetValidator.addMetaSchema(schema_draft_2020_12, 'https://json-schema.org/draft/2020-12/schema');
  jetValidator.addMetaSchema(schema_draft_2020_12, 'draft/2020-12');

  jetValidator.addMetaSchema(schema_draft_2020_12_core, 'https://json-schema.org/draft/2020-12/meta/core');
  jetValidator.addMetaSchema(schema_draft_2020_12_core, 'draft/2020-12/meta/core');
  jetValidator.addMetaSchema(schema_draft_2020_12_applicator, 'https://json-schema.org/draft/2020-12/meta/applicator');
  jetValidator.addMetaSchema(schema_draft_2020_12_applicator, 'draft/2020-12/meta/applicator');
  jetValidator.addMetaSchema(schema_draft_2020_12_unevaluated, 'https://json-schema.org/draft/2020-12/meta/unevaluated');
  jetValidator.addMetaSchema(schema_draft_2020_12_unevaluated, 'draft/2020-12/meta/unevaluated');
  jetValidator.addMetaSchema(schema_draft_2020_12_validation, 'https://json-schema.org/draft/2020-12/meta/validation');
  jetValidator.addMetaSchema(schema_draft_2020_12_validation, 'draft/2020-12/meta/validation');
  jetValidator.addMetaSchema(schema_draft_2020_12_meta_data, 'https://json-schema.org/draft/2020-12/meta/meta-data');
  jetValidator.addMetaSchema(schema_draft_2020_12_meta_data, 'draft/2020-12/meta/meta-data');
  jetValidator.addMetaSchema(schema_draft_2020_12_format_annotation, 'https://json-schema.org/draft/2020-12/meta/format-annotation');
  jetValidator.addMetaSchema(schema_draft_2020_12_format_annotation, 'draft/2020-12/meta/format-annotation');
  jetValidator.addMetaSchema(schema_draft_2020_12_content, 'https://json-schema.org/draft/2020-12/meta/content');
  jetValidator.addMetaSchema(schema_draft_2020_12_content, 'draft/2020-12/meta/content');
}

export function loadAllMetaSchemas(jetValidator) {
  loadDraft06(jetValidator);
  loadDraft07(jetValidator);
  loadDraft201909(jetValidator);
  loadDraft202012(jetValidator);
}
