/**
 * Auto-generated meta-schema loader
 * Generated by: jetvalidator-meta load
 */

export function loadDraft06(jetValidator: any): void;
export function loadDraft07(jetValidator: any): void;
export function loadDraft201909(jetValidator: any): void;
export function loadDraft202012(jetValidator: any): void;
export function loadAllMetaSchemas(jetValidator: any): void;
